apiVersion: v1
kind: ConfigMap
metadata:
  name: akwalibnalkayemms-config
data:
  spring.profiles.active: "prod"
  spring.datasource.url: "jdbc:mysql://mysql-prod:3306/akwalibnalkayemms_prod?useSSL=true&allowPublicKeyRetrieval=false"
  logging.level.com.renault.akwalibnalkayemms: "WARN"
  management.endpoints.web.exposure.include: "health,info,metrics"
  management.endpoint.health.show-details: "never"
