apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akwalibnalkayemms.fullname" . }}
  labels:
    {{- include "akwalibnalkayemms.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "akwalibnalkayemms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "akwalibnalkayemms.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "akwalibnalkayemms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.profiles.active | quote }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.app.database.url | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.app.database.username | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.app.database.password | quote }}
            - name: SPRING_SECURITY_USER_NAME
              value: {{ .Values.app.security.username | quote }}
            - name: SPRING_SECURITY_USER_PASSWORD
              value: {{ .Values.app.security.password | quote }}
            - name: LOGGING_LEVEL_ROOT
              value: {{ .Values.app.logging.level.root | quote }}
            - name: LOGGING_LEVEL_TECH_AMINEABBAOUI_AKWALIBNALKA YEMMS
              value: {{ .Values.app.logging.level.tech.amineabbaoui.akwalibnalkayemms | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
