apiVersion: apps/v1
kind: Deployment
metadata:
  name: akwalibnalkayemms
  labels:
    app: akwalibnalkayemms
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akwalibnalkayemms
  template:
    metadata:
      labels:
        app: akwalibnalkayemms
        version: v1
    spec:
      containers:
      - name: akwalibnalkayemms
        image: akwalibnalkayemms:latest
        ports:
        - containerPort: 9090
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: akwalibnalkayemms-config
              key: spring.profiles.active
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: akwalibnalkayemms-config
              key: spring.datasource.url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: akwalibnalkayemms-secrets
              key: spring.datasource.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: akwalibnalkayemms-secrets
              key: spring.datasource.password
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: akwalibnalkayemms-secrets
              key: spring.security.user.name
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: akwalibnalkayemms-secrets
              key: spring.security.user.password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      imagePullSecrets:
      - name: regcred
