apiVersion: v1
kind: ConfigMap
metadata:
  name: akwalibnalkayemms-config
data:
  spring.profiles.active: "dev"
  spring.datasource.url: "jdbc:mysql://mysql-dev:3306/akwalibnalkayemms_dev?useSSL=false&allowPublicKeyRetrieval=true"
  logging.level.tech.amineabbaoui.akwalibnalkayemms: "DEBUG"
  management.endpoints.web.exposure.include: "health,info,metrics,env,configprops"
