apiVersion: apps/v1
kind: Deployment
metadata:
  name: akwalibnalkayemms
spec:
  template:
    spec:
      containers:
      - name: akwalibnalkayemms
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
