apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: akwalibnalkayemms-dev

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

images:
- name: akwalibnalkayemms
  newTag: dev

replicas:
- name: akwalibnalkayemms
  count: 1
